stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  allow_failure: false
  tags:
    - shell
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - build/

test-v1-job:   # This job runs in the test stage.
  allow_failure: false
  tags:
    - shell
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - cd build
    - echo "Running tests V1..."
    - ctest -R v1

test-v2-job:   # This job runs in the test stage.
  allow_failure: false
  tags:
    - shell
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - cd build
    - echo "Running tests V2..."
    - ctest -R v2